<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ChangeInfo {

  static $swaggerTypes = array(
      'id' => 'int',
      'type' => 'string',
      'typeStr' => 'string',
      'action' => 'string',
      'actionStr' => 'string',
      'page' => 'Page',
      'box' => 'Rectangle',
      'text' => 'string',
      'styleChanges' => 'array[StyleChangeInfo]'

    );

  public $id; // int
  public $type; // string
  public $typeStr; // string
  public $action; // string
  public $actionStr; // string
  public $page; // Page
  public $box; // Rectangle
  public $text; // string
  public $styleChanges; // array[StyleChangeInfo]
  }

