<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SignatureFormSettingsInfo {

  static $swaggerTypes = array(
      'name' => 'string',
      'fieldsInFinalFileName' => 'string',
      'canParticipantDownloadForm' => 'bool',
      'waterMarkText' => 'string',
      'waterMarkImage' => 'string',
      'notifyOwnerOnSign' => 'bool',
      'attachSignedDocument' => 'bool',
      'notifyOtherOnSign' => 'string',
      'canParticipantPrintForm' => 'bool',
      'requireUserAuthForSign' => 'bool',
      'requestUserAuthByPhoto' => 'bool',
      'enableTypedSignature' => 'bool',
      'enableUploadedSignature' => 'bool',
      'requireUserIdentityValidation' => 'bool',
      'canBeCommented' => 'bool',
      'showParticipantCommentInSignedDocument' => 'bool',
      'tags' => 'string'

    );

  public $name; // string
  public $fieldsInFinalFileName; // string
  public $canParticipantDownloadForm; // bool
  public $waterMarkText; // string
  public $waterMarkImage; // string
  public $notifyOwnerOnSign; // bool
  public $attachSignedDocument; // bool
  public $notifyOtherOnSign; // string
  public $canParticipantPrintForm; // bool
  public $requireUserAuthForSign; // bool
  public $requestUserAuthByPhoto; // bool
  public $enableTypedSignature; // bool
  public $enableUploadedSignature; // bool
  public $requireUserIdentityValidation; // bool
  public $canBeCommented; // bool
  public $showParticipantCommentInSignedDocument; // bool
  public $tags; // string
  }

