<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TemplateEditorField {

  static $swaggerTypes = array(
      'name' => 'string',
      'defaultValue' => 'string',
      'fieldtype' => 'string',
      'page' => 'int',
      'rect' => 'Rectangle',
      'selectionPosition' => 'int',
      'selectionLength' => 'int',
      'acceptableValues' => 'array[string]',
      'options' => 'array[TemplateEditorFieldOption]',
      'style' => 'TemplateEditorFieldStyle',
      'isTableMarker' => 'bool',
      'tableNumber' => 'int',
      'tableRow' => 'int',
      'tableColumn' => 'int',
      'tableCell' => 'int'

    );

  public $name; // string
  public $defaultValue; // string
  public $fieldtype; // string
  public $page; // int
  public $rect; // Rectangle
  public $selectionPosition; // int
  public $selectionLength; // int
  public $acceptableValues; // array[string]
  public $options; // array[TemplateEditorFieldOption]
  public $style; // TemplateEditorFieldStyle
  public $isTableMarker; // bool
  public $tableNumber; // int
  public $tableRow; // int
  public $tableColumn; // int
  public $tableCell; // int
  }

