<?php
/**
 *  Copyright 2012 GroupDocs.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TemplateInfo {

  static $swaggerTypes = array(
      'name' => 'string',
      'field_count' => 'int',
      'size' => 'string',
      'fileType' => 'string',
      'docType' => 'string',
      'dependent_questionnaires_count' => 'int',
      'upload_time' => 'string',
      'id' => 'float',
      'guid' => 'string'

    );

  public $name; // string
  public $field_count; // int
  public $size; // string
  public $fileType; // string
  public $docType; // string
  public $dependent_questionnaires_count; // int
  public $upload_time; // string
  public $id; // float
  public $guid; // string
  }

